# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: XJTLU Open Source Mirror
school: XJTLU
# brand: MITS
operator: XJTLU MITS
author: XJTLU MITS Association
desc: MITS provides open-source software mirroring and Linux mirroring source code services for school users, making it
    easier to obtain open-source software. XJTLU MITS maintains this mirror station.
logo: false
meow_404: true
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirrors.xjtlu.edu.cn"
hostname: "mirrors.xjtlu.edu.cn"
pypi: "pypi.mirrors.xjtlu.edu.cn"
hide_navbar: false
hide_download: false
hide_server_status: false

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

sass:
    sass_dir: static/css

plugins:
    - jekyll-babel
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]
