# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 西交利物浦大学开源软件镜像站
school: 西交利物浦大学
brand: XJTLU Open Source Mirror
operator: XJTLU MITS
author: XJTLU MITS Association
desc: 提供高质量的开源软件镜像、Linux 镜像源服务，帮助用户更方便地获取开源软件。
logo: false
meow_404: true
issue_tag: mits
permalink: "/:categories/:title/"
url: "https://mirrors.mits.xjtlu.edu.cn"
hostname: "mirrors.mits.xjtlu.edu.cn"
urlv4: "https://mirrors4.mits.xjtlu.edu.cn"
urlv6: "https://mirrors6.mits.xjtlu.edu.cn"
aosp: "aosp.mits.xjtlu.edu.cn"
arch_archive: "arch-archive.mits.xjtlu.edu.cn"
aur: "aur.mits.xjtlu.edu.cn"
pypi: "pypi.mits.xjtlu.edu.cn"
homelink: "https://guide.xjtlu.edu.cn"
hide_navbar: false
hide_download: false
hide_server_status: false

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

plugins:
    - jekyll-babel
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]
